services:
  gateway:
    image: ghcr.io/ismailcanuslu/librelane-gateway:latest
    restart: unless-stopped
    container_name: librelane-gateway
    networks:
      - librelane-network

networks:
  librelane-network:
    external: true
